### ISSUE TITLE
useless with fireyejs.js

### ISSUE THREAD

**Issue by ycq0125** [ceres-c/bulldozer#1]
https://g.alicdn.com/AWSC/fireyejs/1.221.0/fireyejs.js

**Comment by ceres-c** [comment]
From the [README](https://github.com/ceres-c/bulldozer#readme)
> A deobfuscator/decompiler written in JavaScript for JavaScript "binaries", <ins>currently targeted at collina.js</ins> from AliExpress.

You can expand the project to support this file. This issue is lacking any detail, so I'm not going to elaborate further. If you need some help, feel free to comment with your questions or doubts

**Comment by ycq0125** [comment]
This is an upgraded version of Collins.js，I will try to update your code to support the revised version.
